import fs from 'node:fs'

import { Action } from '../source'

const enchantments: {
	/** can be created via anvil */
	anvil: number[]
	/** these levels can exist on items */
	applied: number[]
	id: string
	/** can be obtained for free from the enchantment table */
	free: number[]
	/** exist in item form */
	item: number[]
	name: string
}[] = [
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'ABSORB',
		item: [1],
		name: 'Absorb',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3, 4, 5],
		id: 'AIMING',
		item: [],
		name: 'Dragon Tracer',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'ANGLER',
		item: [6],
		name: 'Angler',
	},
	{
		anvil: [],
		applied: [1],
		free: [1],
		id: 'AQUA_AFFINITY',
		item: [],
		name: 'Aqua Affinity',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'ARCANE',
		item: [6],
		name: 'Woodsplitter',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'BANE_OF_ARTHROPODS',
		item: [6, 7],
		name: 'Bane of Arthropods',
	},
	{
		anvil: [4, 5],
		applied: [3, 4, 5],
		free: [],
		id: 'BIG_BRAIN',
		item: [3, 4, 5],
		name: 'Big Brain',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'BLAST_PROTECTION',
		item: [6, 7],
		name: 'Blast Protection',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'BLESSING',
		item: [6],
		name: 'Blessing',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'BUG_BLENDER',
		item: [1, 2, 3, 4, 5],
		name: 'Bug Blender',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'CASTER',
		item: [6],
		name: 'Caster',
	},
	{
		anvil: [5],
		applied: [4, 5],
		free: [],
		id: 'CAYENNE',
		item: [4, 5],
		name: 'Cayenne',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'CHAMPION',
		item: [1],
		name: 'Champion',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3],
		id: 'CHANCE',
		item: [4, 5],
		name: 'Chance',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5, 6],
		free: [],
		id: 'CHARM',
		item: [1, 2, 3, 4, 5],
		name: 'Charm',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'CLEAVE',
		item: [1, 2, 3, 4, 5, 6],
		name: 'Cleave',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'COMPACT',
		item: [1],
		name: 'Compact',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'CORRUPTION',
		item: [1, 2, 3, 4, 5],
		name: 'Corruption',
	},
	{
		anvil: [],
		applied: [5],
		free: [],
		id: 'COUNTER_STRIKE',
		item: [5], // FIXME: 3-4 exist on SF
		name: 'Counter-Strike',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'CRITICAL',
		item: [6, 7],
		name: 'Critical',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'CUBISM',
		item: [6],
		name: 'Cubism',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'CULTIVATING',
		item: [1],
		name: 'Cultivating',
	},
	// { id: 'CURSE_OF_VANISHING', max: 0, min: 0 }, // FIXME: seems bugged
	{
		anvil: [2, 3],
		applied: [1, 2, 3, 4],
		free: [],
		id: 'DEDICATION',
		item: [1, 2, 3, 4],
		name: 'Dedication',
	},
	{
		anvil: [],
		applied: [5],
		free: [],
		id: 'DELICATE',
		item: [5],
		name: 'Delicate',
	},
	{
		anvil: [],
		applied: [1, 2, 3],
		free: [1, 2, 3],
		id: 'DEPTH_STRIDER',
		item: [],
		name: 'Depth Strider',
	},
	{
		anvil: [2, 3],
		applied: [1, 2, 3],
		free: [],
		id: 'DIVINE_GIFT',
		item: [1, 2, 3],
		name: 'Divine Gift',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'DRAGON_HUNTER',
		item: [1, 2, 3, 4, 5, 6],
		name: 'Gravity',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [1, 2, 3, 4, 5],
		id: 'EFFICIENCY',
		item: [],
		name: 'Efficiency',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'ENDER_SLAYER',
		item: [6],
		name: 'Ender Slayer ',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'EXECUTE',
		item: [6],
		name: 'Execute',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3],
		id: 'EXPERIENCE',
		item: [4, 5],
		name: 'Experience',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'EXPERTISE',
		item: [1],
		name: 'Expertise',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'FEAST',
		item: [1, 2, 3, 4, 5],
		name: 'Feast',
	},
	{
		anvil: [7, 8, 9, 10],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20], // 20 = Spring Boots
		free: [1, 2, 3, 4, 5],
		id: 'FEATHER_FALLING',
		item: [6, 7, 8, 9, 10],
		name: 'Feather Falling',
	},
	{
		anvil: [2, 3, 4, 5, 6, 7, 8, 9, 10],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'FEROCIOUS_MANA',
		item: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		name: 'Ferocious Mana',
	},
	{
		anvil: [],
		applied: [1, 2, 3],
		free: [1, 2],
		id: 'FIRE_ASPECT',
		item: [3],
		name: 'Fire Aspect',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'FIRE_PROTECTION',
		item: [6, 7],
		name: 'Fire Protection',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3, 4],
		id: 'FIRST_STRIKE',
		item: [5],
		name: 'First Strike',
	},
	{
		anvil: [],
		applied: [1, 2],
		free: [1, 2],
		id: 'FLAME',
		item: [],
		name: 'Flame',
	},
	{
		anvil: [4, 5],
		applied: [3, 4, 5],
		free: [],
		id: 'FOREST_PLEDGE',
		item: [3, 4, 5],
		name: 'Forest Pledge',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4],
		free: [1, 2, 3],
		id: 'FORTUNE',
		item: [4],
		name: 'Fortune',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'FRAIL',
		item: [6],
		name: 'Frail',
	},
	// { id: 'FROST_WALKER', max: 2, min: 1 }, // FIXME: this seems to have been removed
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'GIANT_KILLER',
		item: [6, 7],
		name: 'Giant Killer',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'GREEN_THUMB',
		item: [1, 2, 3, 4, 5],
		name: 'Green Thumb',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'GROWTH',
		item: [6, 7],
		name: 'Growth',
	},
	{
		anvil: [2, 3, 4, 5, 6, 7, 8, 9, 10],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'HARDENED_MANA',
		item: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		name: 'Hardened Mana',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'HARVESTING',
		item: [6],
		name: 'Harvesting',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'HECATOMB',
		item: [1],
		name: 'Hecatomb',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ICE_COLD',
		item: [1, 2, 3, 4, 5],
		name: 'Ice Cold',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3, 4, 5],
		id: 'IMPALING',
		item: [],
		name: 'Impaling',
	},
	{
		anvil: [6, 7, 8, 9, 10],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [1, 2, 3, 4, 5],
		id: 'INFINITE_QUIVER',
		item: [5, 6, 7, 8, 9, 10],
		name: 'Infinite Quiver',
	},
	{
		anvil: [],
		applied: [1, 2],
		free: [1, 2],
		id: 'KNOCKBACK',
		item: [],
		name: 'Knockback',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'LAPIDARY',
		item: [1, 2, 3, 4, 5],
		name: 'Lapidary',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'LETHALITY',
		item: [6],
		name: 'Lethality',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3],
		id: 'LIFE_STEAL',
		item: [4, 5],
		name: 'Life Steal',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3],
		id: 'LOOTING',
		item: [4, 5],
		name: 'Looting',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'LUCK',
		item: [6, 7],
		name: 'Luck',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'LUCK_OF_THE_SEA',
		item: [6],
		name: 'Luck of the Sea',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'LURE',
		item: [6],
		name: 'Lure',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'MAGMARIZER',
		item: [6],
		name: 'Magmarizer',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'MAGNET',
		item: [6],
		name: 'Magnet',
	},
	{
		anvil: [2, 3],
		applied: [1, 2, 3],
		free: [],
		id: 'MANA_STEAL',
		item: [1, 2, 3],
		name: 'Mana Steal',
	},
	{
		anvil: [2, 3, 4, 5, 6, 7, 8, 9, 10],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'MANA_VAMPIRE',
		item: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		name: 'Mana Vampire',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'OVERLOAD',
		item: [1, 2, 3, 4, 5],
		name: 'Overload',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'PALEONTOLOGIST',
		item: [1, 2, 3, 4, 5],
		name: 'Paleontologist',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5, 6],
		free: [],
		id: 'PESTERMINATOR',
		item: [1, 2, 3, 4, 5],
		name: 'Pesterminator',
	},
	{
		anvil: [],
		applied: [1],
		free: [1],
		id: 'PIERCING',
		item: [],
		name: 'Piercing',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'PISCARY',
		item: [6],
		name: 'Piscary',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'POWER',
		item: [6, 7],
		name: 'Power',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'PRISTINE',
		item: [1, 2, 3, 4, 5],
		name: 'Prismatic',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'PROJECTILE_PROTECTION',
		item: [6, 7],
		name: 'Projectile Protection',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4],
		id: 'PROSECUTE',
		item: [5, 6],
		name: 'Prosecute',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'PROSPERITY',
		item: [1, 2, 3, 4, 5],
		name: 'Prosperity',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'PROTECTION',
		item: [6, 7],
		name: 'Protection',
	},
	{
		anvil: [],
		applied: [1, 2],
		free: [1, 2],
		id: 'PUNCH',
		item: [],
		name: 'Punch',
	},
	{
		anvil: [4, 5],
		applied: [3, 4, 5],
		free: [],
		id: 'QUANTUM',
		item: [3, 4, 5],
		name: 'Quantum',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'QUICK_BITE',
		item: [1, 2, 3, 4, 5],
		name: 'Quick Bite',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'REFLECTION',
		item: [1, 2, 3, 4, 5],
		name: 'Reflection',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'REJUVENATE',
		item: [1, 2, 3, 4, 5],
		name: 'Rejuvenate',
	},
	{
		anvil: [],
		applied: [1],
		free: [],
		id: 'REPLENISH',
		item: [1],
		name: 'Replenish',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4],
		free: [1, 2, 3],
		id: 'RESPIRATION',
		item: [4],
		name: 'Respiration',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'RESPITE',
		item: [1, 2, 3, 4, 5],
		name: 'Respite',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3],
		id: 'SCAVENGER',
		item: [4, 5],
		name: 'Scavenger',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5, 6],
		free: [],
		id: 'SCUBA',
		item: [1, 2, 3, 4, 5],
		name: 'Scuba',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'SHARPNESS',
		item: [6, 7],
		name: 'Sharpness',
	},
	{
		anvil: [],
		applied: [1],
		free: [1],
		id: 'SILK_TOUCH',
		item: [],
		name: 'Silk Touch',
	},
	{
		anvil: [4, 5],
		applied: [3, 4, 5],
		free: [],
		id: 'SMALL_BRAIN',
		item: [3, 4, 5],
		name: 'Small Brain',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'SMARTY_PANTS',
		item: [1, 2, 3, 4, 5],
		name: 'Smarty Pants',
	},
	{
		anvil: [],
		applied: [1],
		free: [1],
		id: 'SMELTING_TOUCH',
		item: [],
		name: 'Smelting Touch',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'SMITE',
		item: [6],
		name: 'Smite',
	},
	{
		anvil: [1, 2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'SMOLDERING',
		item: [1, 2, 3, 4, 5],
		name: 'Smoldering',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4],
		free: [1, 2, 3],
		id: 'SNIPE',
		item: [4],
		name: 'Snipe',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'SPIKED_HOOK',
		item: [6],
		name: 'Spiked Hook',
	},
	{
		anvil: [],
		applied: [1],
		free: [],
		id: 'STEALTH',
		item: [1],
		name: 'Stealth',
	},
	{
		anvil: [2, 3, 4, 5, 6, 7, 8, 9, 10],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'STRONG_MANA',
		item: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		name: 'Strong Mana',
	},
	{
		anvil: [2, 3],
		applied: [1, 2, 3],
		free: [],
		id: 'SUGAR_RUSH',
		item: [1, 2, 3],
		name: 'Sugar Rush',
	},
	// { id: 'SUNDER', max: 6, min: 1 }, // FIXME: this enchantment was removed from skyblock
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3],
		id: 'SYPHON',
		item: [4, 5],
		name: 'Drain',
	},
	{
		anvil: [3],
		applied: [2, 3],
		free: [],
		id: 'TABASCO',
		item: [2, 3],
		name: 'Tabasco',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4],
		free: [1, 2, 3],
		id: 'THORNS',
		item: [],
		name: 'Thorns',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'THUNDERBOLT',
		item: [6, 7],
		name: 'Thunderbolt',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'THUNDERLORD',
		item: [6, 7],
		name: 'Thunderlord,',
	},
	{
		anvil: [2, 3],
		applied: [1, 2, 3],
		free: [],
		id: 'TIDAL',
		item: [1, 2, 3],
		name: 'Tidal',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'TITAN_KILLER',
		item: [6, 7],
		name: 'Titan Killer',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
		free: [],
		id: 'TOXOPHILITE',
		item: [1],
		name: 'Toxophilite',
	},
	{
		anvil: [5],
		applied: [4, 5],
		free: [],
		id: 'TRANSYLVANIAN',
		item: [4, 5],
		name: 'Transylvanian',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5],
		free: [1, 2, 3, 4],
		id: 'TRIPLE_STRIKE',
		item: [5],
		name: 'Triple-Strike',
	},
	{
		anvil: [],
		applied: [1],
		free: [],
		id: 'TRUE_PROTECTION',
		item: [1],
		name: 'True Protection',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_CACTUS',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Cactus',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_CANE',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Cane',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_CARROT',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Carrot',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_COCO',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Cocoa',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_MELON',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Melon',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_MOONFLOWER',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Moonflower',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_MUSHROOMS',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Mushrooms',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_POTATO',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Potato',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_PUMPKIN',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Pumpkin',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_ROSE',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Rose',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_SUNFLOWER',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Sunflower',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_WARTS',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Warts',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'TURBO_WHEAT',
		item: [1, 2, 3, 4, 5],
		name: 'Turbo-Wheat',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_BANK',
		item: [1, 2, 3, 4, 5],
		name: 'Bank',
	},
	{
		anvil: [4, 5],
		applied: [3, 4, 5],
		free: [],
		id: 'ULTIMATE_BOBBIN_TIME',
		item: [3, 4, 5],
		name: "Bobbin' Time",
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_CHIMERA',
		item: [1, 2, 3, 4, 5],
		name: 'Chimera',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4],
		free: [],
		id: 'ULTIMATE_COMBO',
		item: [1, 2, 3, 4, 5],
		name: 'Combo',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_CROP_FEVER',
		item: [1, 2, 3, 4, 5],
		name: 'Crop Fever',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_FATAL_TEMPO',
		item: [1, 2, 3, 4, 5],
		name: 'Fatal Tempo',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_FIRST_IMPRESSION',
		item: [1, 2, 3, 4, 5],
		name: 'First Impression',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_FLASH',
		item: [1, 2, 3, 4, 5],
		name: 'Flash',
	},
	{
		anvil: [2, 3],
		applied: [1, 2, 3],
		free: [],
		id: 'ULTIMATE_FLOWSTATE',
		item: [1, 2, 3],
		name: 'Flowstate',
	},
	{
		anvil: [5],
		applied: [4, 5],
		free: [],
		id: 'ULTIMATE_HABANERO_TACTICS',
		item: [4, 5],
		name: 'Habanero Tactics',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_INFERNO',
		item: [1, 2, 3, 4, 5],
		name: 'Inferno',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_JERRY',
		item: [1, 2, 3, 4, 5],
		name: 'Ultimate Jerry',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_LAST_STAND',
		item: [1, 2, 3, 4, 5],
		name: 'Last Stand',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_LEGION',
		item: [1, 2, 3, 4, 5],
		name: 'Legion',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_MISSILE',
		item: [1, 2, 3, 4, 5],
		name: 'Missile',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_NO_PAIN_NO_GAIN',
		item: [1, 2, 3, 4, 5],
		name: 'No Pain No Gain',
	},
	{
		anvil: [],
		applied: [1],
		free: [],
		id: 'ULTIMATE_ONE_FOR_ALL',
		item: [1], // FIXME: OFA 0 exists in bazaar API
		name: 'One For All',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_REFRIGERATE',
		item: [1, 2, 3, 4, 5],
		name: 'Refrigerate',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_REITERATE',
		item: [1, 2, 3, 4, 5],
		name: 'Duplex',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_REND',
		item: [1, 2, 3, 4, 5],
		name: 'Rend',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_SOUL_EATER',
		item: [1, 2, 3, 4, 5],
		name: 'Soul Eater',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_SUNSET',
		item: [1, 2, 3, 4, 5],
		name: 'Sunset',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_SWARM',
		item: [1, 2, 3, 4, 5],
		name: 'Swarm',
	},
	{
		anvil: [5],
		applied: [4, 5],
		free: [],
		id: 'ULTIMATE_THE_ONE',
		item: [4, 5],
		name: 'The One',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_WISDOM',
		item: [1, 2, 3, 4, 5],
		name: 'Wisdom',
	},
	{
		anvil: [2, 3, 4, 5],
		applied: [1, 2, 3, 4, 5],
		free: [],
		id: 'ULTIMATE_WISE',
		item: [1, 2, 3, 4, 5],
		name: 'Ultimate Wise',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6],
		free: [1, 2, 3, 4, 5],
		id: 'VAMPIRISM',
		item: [6],
		name: 'Vampirism',
	},
	{
		anvil: [],
		applied: [1, 2, 3, 4, 5, 6, 7],
		free: [1, 2, 3, 4, 5],
		id: 'VENOMOUS',
		item: [6],
		name: 'Venomous',
	},
	{
		anvil: [4, 5],
		applied: [3, 4, 5],
		free: [],
		id: 'VICIOUS',
		item: [3, 4, 5],
		name: 'Vicious',
	},
	// { id: 'WITHER_HUNTER', max: 0, min: 0 }, // FIXME: this exists in the bazaar API but nowhere else...
]

enchantments.sort((a, b) => a.id.localeCompare(b.id))

const recipes: Action[] = []

for (const enchantment of enchantments) {
	for (const entry of enchantment.anvil) {
		recipes.push({
			inputs: [
				{
					amount: 2,
					id: `ENCHANTMENT_${enchantment.id}_${entry - 1}`,
					type: 'item',
				},
			],
			outputs: [
				{
					amount: 1,
					id: `ENCHANTMENT_${enchantment.id}_${entry}`,
					type: 'item',
				},
			],
			place: [
				{
					left: {
						amount: 1,
						id: `ENCHANTMENT_${enchantment.id}_${entry - 1}`,
						type: 'item',
					},
					right: {
						amount: 1,
						id: `ENCHANTMENT_${enchantment.id}_${entry - 1}`,
						type: 'item',
					},
					type: 'anvil',
				},
			],
		})
	}
}

fs.writeFileSync(
	__dirname + '/../data/enchantments.json',
	JSON.stringify(
		{
			$schema: './$schema.json',
			actions: recipes,
		},
		null,
		'\t',
	),
)
