export enum PrivateIslandType {
	BARN = 'BARN',
	DESERT = 'DESERT',
	FARMING = 'FARMING',
	MINING = 'MINING',
	MINING_FOREST = 'MINING_FOREST',
	NETHER = 'NETHER',
	NETHER_WART = 'NETHER_WART',
	POND = 'POND',
	WINTER = 'WINTER',
}

export enum CrystalType {
	DESERT_ISLAND = 'DESERT_ISLAND',
	FARM = 'FARM',
	FISHING = 'FISHING',
	FOREST_ISLAND = 'FOREST_ISLAND',
	MITHRIL = 'MITHRIL',
	NETHER_WART_ISLAND = 'NETHER_WART_ISLAND',
	RESOURCE_REGENERATOR = 'RESOURCE_REGENERATOR',
	WHEAT_ISLAND = 'WHEAT_ISLAND',
	WINTER_ISLAND = 'WINTER_ISLAND',
	WOODCUTTING = 'WOODCUTTING',
}
