export enum SkillType {
	COMBAT = 'COMBAT',
	ENCHANTING = 'ENCHANTING',
	FARMING = 'FARMING',
	FISHING = 'FISHING',
	FORAGING = 'FORAGING',
	HUNTING = 'HUNTING',
	MINING = 'MINING',
	SOCIAL = 'SOCIAL',
}
